import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/ui/tubelight-navbar"
import { HeroGeometric } from "@/components/ui/shape-landing-hero";

const navItems = [
  { name: 'Home', url: '/'},
  { name: 'About', url: '#' },
  { name: 'Projects', url: '#' },
  { name: 'Resume', url: '#' }
]


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/* <HeroGeometric badge="Kokonut UI"
            title1 = "Vincenzo Tulimieri"
            title2 = "Full Stack Developer" /> */}
        <header>
          <NavBar items={navItems} />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
